name: Update README with GitHub Stats
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Configure Git
        run: |
          git config --global user.email "amitcode98@gmail.com"
          git config --global user.name "amitk2108"
      
      - name: Update README with GitHub Stats
        run: |
          curl -sL "https://github-readme-stats.vercel.app/api?username=Amitk2108&show_icons=true&locale=en&theme=tokyonight" > README.md
          curl -sL "https://github-readme-streak-stats.herokuapp.com/?user=amitk2108&&theme=tokyonight" >> README.md
          curl -sL "https://github-readme-stats.vercel.app/api/top-langs?username=amitk2108&show_icons=true&locale=en&layout=compact&theme=tokyonight" >> README.md
          echo "\n[![trophy](https://github-profile-trophy.vercel.app/?username=Amitk2108)](https://github.com/ryo-ma/github-profile-trophy)" >> README.md
          echo "\n<img src='https://github-readme-activity-graph.vercel.app/graph?username=Amitk2108&bg_color=161b22&color=ffffff&line=d5d5d5&point=a76c6c&area=true&hide_border=true&hide_title=true' />" >> README.md
          git add README.md
          git commit -m "Update README with latest GitHub stats and activity graph" || echo "No changes to commit"
          git push
