name: Update README with GitHub Stats
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Update README with GitHub Stats
        run: |
          curl -sL "https://github-readme-stats.vercel.app/api?username=Amitk2108&show_icons=true&locale=en&theme=tokyonight" > README.md
          curl -sL "https://github-readme-streak-stats.herokuapp.com/?user=amitk2108&&theme=tokyonight" >> README.md
          curl -sL "https://github-readme-stats.vercel.app/api/top-langs?username=amitk2108&show_icons=true&locale=en&layout=compact&theme=tokyonight" >> README.md
          git add README.md
          git commit -m "Update README with latest GitHub stats" || echo "No changes to commit"
          git push

